<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'IOET\Acme\PayRoll\Employee\Application\GetAllEmployeesName\GetAllEmployeesNameQueryHandler' shared autowired service.

return $this->privates['IOET\\Acme\\PayRoll\\Employee\\Application\\GetAllEmployeesName\\GetAllEmployeesNameQueryHandler'] = new \IOET\Acme\PayRoll\Employee\Application\GetAllEmployeesName\GetAllEmployeesNameQueryHandler(new \IOET\Acme\PayRoll\Employee\Application\GetAllEmployeesName\AllEmployeesNameFilter(($this->privates['IOET\\Acme\\PayRoll\\Employee\\Infrastructure\\TextFileEmployeeWorkedHoursRepository'] ?? ($this->privates['IOET\\Acme\\PayRoll\\Employee\\Infrastructure\\TextFileEmployeeWorkedHoursRepository'] = new \IOET\Acme\PayRoll\Employee\Infrastructure\TextFileEmployeeWorkedHoursRepository()))));
