<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5OtMLEV\srcIOET_Apps_Acme_PayRoll_v1_Employee_PayRollKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5OtMLEV/srcIOET_Apps_Acme_PayRoll_v1_Employee_PayRollKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5OtMLEV.legacy');

    return;
}

if (!\class_exists(srcIOET_Apps_Acme_PayRoll_v1_Employee_PayRollKernelDevDebugContainer::class, false)) {
    \class_alias(\Container5OtMLEV\srcIOET_Apps_Acme_PayRoll_v1_Employee_PayRollKernelDevDebugContainer::class, srcIOET_Apps_Acme_PayRoll_v1_Employee_PayRollKernelDevDebugContainer::class, false);
}

return new \Container5OtMLEV\srcIOET_Apps_Acme_PayRoll_v1_Employee_PayRollKernelDevDebugContainer([
    'container.build_hash' => '5OtMLEV',
    'container.build_id' => 'f384d5a9',
    'container.build_time' => 1629170753,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5OtMLEV');
